Section/services
5fpro/apollo pull request #4
Opened 2017-05-12 00:47 UTC by irene84111

@marsz 剛剛搞懂了 XD 所以現在應該沒有問題了，再麻煩你囉 🙌

2017-05-13 12:15 UTC, marsz requested changes
@irene84111 我 review 完了
有兩個 comment 給你
改完再讓我 review 一次

然後，你之後會想要定期送 PR 嗎?
還是想要繼續在目前的 PR 上推 commit 上來?
兩者我都 ok 
看你習慣

2017-05-13 12:15 UTC, marsz commented on source/layouts/_head.slim
> +link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Questrial"
一般外部連結如果有支援 https 和 http 的話
都會寫成這樣

```
href="//fonts.googleapis.com/css?family=Questrial"
```

意思就是看你的網站現在是 http 還是 https 他會自動去對應
因為在 http 的網站上，無法載入 https 的外部連結
還是相反的情況我忘了

當然現在大部分網站都會強制把 http 轉到 https
可是在測試環境下會是用 http
所以走 // 開頭就萬無一失了

2017-05-13 12:15 UTC, marsz commented on source/stylesheets/_mixin.sass
> +	transition:         $transition
indent format 一般我們都是用 2 spaces
無論寫 html, slim, js ,css, sass/scss, ruby 等，全都是 2 spaces indent
所以看要不要趁現在檔案還沒有很多的時候，統一一下 XD

2017-05-15 02:25 UTC, irene84111 commented
@marsz 上述問題已經修正囉

我習慣會定期送 PR 上來，這樣必較有工作告一個段落的感覺 XDD
所以這個你會 merge 回 develop 嗎？這樣我之後就會直接從 develop 繼續開分支出來

2017-05-15 06:18 UTC, marsz approved these changes

2017-05-15 06:18 UTC, marsz commented
@irene84111 會的
我 review 完後就會直接幫你 merge

2017-05-15 06:18 UTC, merged