Section/projects
5fpro/apollo pull request #6
Opened 2017-05-18 11:03 UTC by irene84111

@marsz 
補上各個服務的簡介，不過字數比我想像的多 ...XD 所以目前看起來有點小亂 QQ
另外，新增 Projects 的部分，View More  的部分還沒有補上 JS

2017-05-20 09:45 UTC, marsz requested changes

2017-05-20 09:45 UTC, marsz commented on source/stylesheets/_section-projects.sass
> +#projects
這個檔案的 indent 好像跑掉了喔 XD

2017-05-20 09:45 UTC, marsz commented on source/layouts/_services.slim
> +    .section-title Services
section title 可以用 `<h2>`
在 SEO 裡面， 某些 HTML 標籤其實具備不同的意義
h1: 一個網頁裡面只能有一個 h1，通常會是具代表性的內容，例如新聞頁就會是包標題，產品頁就會是包產品名稱，而首頁通常都是包 logo 或公司名稱
h2: 通常用於副標題或條列式重點，在我們官網裡面的話，應該就是 slogan 或 hero image 區塊的內文，一個網頁內可以有多個 h2，但不要太多
h3: 區塊的標題，這一行就可以用 h3 來取代 `.section-title`
b, em: 強調的關鍵字，可能我之後會在服務內容裡面挑幾個關鍵字包 em 上去
p: 段落文字，像服務內容、專案介紹文字都可以用 p 包

大概就這幾個比較重要的，不過 SEO 現在已經不像以前那麼重要了 XD
所以我們現在也沒有很要求設計師 follow 這些
不過若你有想要練習這方面的專業能力的話，可以嘗試看看
google 和 bing 官方都有提供工具，可以分析你網頁的 html tag 結構並且給出建議
之後上 staging 可以弄一份報告給你看

2017-05-20 09:47 UTC, marsz commented
@irene84111 我 review ，主要是 indent 那邊要調整，其他的都沒問題，本來想說像是案例內容包含圖片可不可以抽出來變成變數，但發現你一次做到位，真是太專業了 XD
另外我有給一些 SEO 建議，這部份就看你有沒有想要在這次做
最主要在上線後，用官方提供的工具去調整 seo tag 會比較快理解
現在即使現階段不考慮 SEO tag 也無所謂

2017-05-22 02:28 UTC, irene84111 commented on source/stylesheets/_section-projects.sass
> +#projects
Sorry 下次會注意 Orz

2017-05-22 02:29 UTC, irene84111 commented on source/layouts/_services.slim
> +    .section-title Services
我知道應該下個 heading，但不知道用哪一個比較合適，感謝詳細的資料補充 💪
期待報告 👀

2017-05-22 03:24 UTC, irene84111 commented
@marsz 
Changes requests 都修正了，還有微調了一點東西
在能力範圍能做到的我盡量做到好囉 XD

2017-05-22 10:51 UTC, marsz approved these changes

2017-05-22 10:51 UTC, marsz commented
@irene84111 已 merge

2017-05-22 10:51 UTC, merged