Section/clients
5fpro/apollo pull request #7
Opened 2017-05-25 11:10 UTC by irene84111

這次有做全面性的調整，Projects 也全部都補上囉
目前進行到 Clients 的部分，還沒有全部調整好

2017-05-31 17:27 UTC, marsz requested changes
@irene84111 已 review
下次發 PR 記得 tag ，沒收到通知我會忘記看 Q_Q

2017-05-31 17:27 UTC, marsz commented on source/layouts/_projects.slim
> +      - data.project.projects.drop(3).each do |project|
如果之後變成有 8 個或 7 個的話，改完 yaml 還要來這裡改數字
有一個方式給你參考

```slim
- total = data.project.projects.size
- show_count = 3
- hidden_count = total - 3
....
section#projects
  ....
  - data.project.projects.take(show_count).each do |project|
    ...
  - data.project.projects.take(hidden_count).each do |project|
```

2017-05-31 17:28 UTC, marsz commented
@irene84111 今天禮拜四，你有要繼續切的話，就先在這條切好了，我週五 review 完若沒問題就直接幫你 merge 了

2017-06-01 03:44 UTC, irene84111 commented on source/layouts/_projects.slim
> +      - data.project.projects.drop(3).each do |project|
`.drop(n)` 不就是捨棄前 n 項嗎？
設計上是一開始只顯示前三項，所以不管日後增減項目，應該也不引響頁面的顯示？還是我的理解有錯誤 😨
如果要改變順序，只需要調整 yaml 檔案的順序即可

2017-06-01 03:53 UTC, marsz commented on source/layouts/_projects.slim
> +      - data.project.projects.drop(3).each do |project|
@irene84111 抱歉，我想錯了 XD 這樣就沒問題了
立馬來 merge

2017-06-01 03:53 UTC, marsz approved these changes

2017-06-01 03:54 UTC, merged

2017-06-01 03:54 UTC, marsz commented
@irene84111  merged